### ISSUE TITLE
老的脚本报错

### ISSUE THREAD

**Issue by crhope** [Lynn-Becky/v6_only#2]
环境：wap v6 hk1刀鸡，debian系统

apt install -y curl && bash <(curl -Ls https://raw.githubusercontent.com/Lynn-Becky/v6_only/main/v4old.sh)

选2，运行老的官方warp脚本报错
Processing triggers for libc-bin (2.28-10) ...##############################################################..] 
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for mime-support (3.62) ...
Error: "Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?"
Error: "Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?"
Error: "Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?"
Error: "Unable to connect to CloudflareWARP daemon. Maybe the daemon is not running?"
error: unrecognized subcommand 'enable-always-on'

  tip: some similar subcommands exist: 'enable-wifi', 'enable-dns-log'

Usage: warp-cli [OPTIONS] <COMMAND>

For more information, try '--help'.

**Comment by Lynn-Becky** [comment]
你看看是不是网络连通性问题，刚刚我测试了没问题的
